module.exports = {
  'Mathematics': [
    { id: 'math10_algebra', grade: 10, stream: 'Science', topic: 'Algebraic Expressions & Equations', tutoringPrompt: 'Act as an expert Grade 10 Mathematics tutor. Explain trinomial factorization and expanding brackets using the South African CAPS curriculum level. Provide detailed core notes and at least 3 step-by-step worked examples. Return JSON: {"explanation": "string", "examples": "string", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 rigorous Grade 10 Algebra questions. Return JSON array.' },
    { id: 'math10_trig', grade: 10, stream: 'Science', topic: 'Trigonometry: Right-Angled Triangles', tutoringPrompt: 'Act as an expert Grade 10 Mathematics tutor. Explain SOHCAHTOA and solving for sides/angles in right-angled triangles. Use Grade 10 CAPS level. Provide detailed notes and 3 worked examples. Return JSON: {"explanation": "string", "examples": "string", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 Grade 10 Trig questions. Return JSON array.' },
    { id: 'math11_functions', grade: 11, stream: 'Science', topic: 'Functions: Parabolas & Hyperbolas', tutoringPrompt: 'Explain standard form shifts for Grade 11. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'math11_trig', grade: 11, stream: 'Science', topic: 'Trigonometric Sine & Cosine Rules', tutoringPrompt: 'Explain Sine and Area rules for Grade 11. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'math12_calculus', grade: 12, stream: 'Science', topic: 'Differential Calculus', tutoringPrompt: 'Explain first principles for Grade 12. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'math12_geometry', grade: 12, stream: 'Science', topic: 'Euclidean Geometry: Proportionality', tutoringPrompt: 'Explain similarity theorems for Grade 12. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' }
  ],
  'Physical Sciences': [
    { id: 'phys10_vectors', grade: 10, stream: 'Science', topic: 'Vectors in 1D', tutoringPrompt: 'Act as an expert Grade 10 Physical Science tutor. Explain vector addition, direction, and magnitude in 1D. Provide core notes and at least 3 detailed worked examples. Return JSON: {"explanation": "string", "examples": "string", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 rigorous Grade 10 Science questions. Return JSON array.' },
    { id: 'phys11_newton', grade: 11, stream: 'Science', topic: 'Newtons Laws of Motion', tutoringPrompt: 'Explain F=ma for Grade 11. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'phys11_intermolecular', grade: 11, stream: 'Science', topic: 'Intermolecular Forces', tutoringPrompt: 'Explain Hydrogen bonding for Grade 11. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'phys12_projectile', grade: 12, stream: 'Science', topic: 'Vertical Projectile Motion', tutoringPrompt: 'Explain falling objects for Grade 12. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'phys12_equilibrium', grade: 12, stream: 'Science', topic: 'Chemical Equilibrium (Kc)', tutoringPrompt: 'Explain Le Chateliers principle for Grade 12. Return JSON: {"explanation": "text", "formula": "LaTeX"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' }
  ],
  'Life Sciences': [
    { id: 'life10_molecules', grade: 10, stream: 'Science', topic: 'Molecules of Life', tutoringPrompt: 'Act as an expert Grade 10 Life Science tutor. Explain organic molecules like proteins, carbohydrates, and lipids. Provide comprehensive notes and detailed examples. Return JSON: {"explanation": "string", "examples": "string", "formula": "none"}.', questionPrompt: 'Generate 3 detailed Grade 10 Life Science questions. Return JSON array.' },
    { id: 'life11_micro', grade: 11, stream: 'Science', topic: 'Biodiversity: Micro-organisms', tutoringPrompt: 'Explain viruses and bacteria for Grade 11. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'life11_repro', grade: 11, stream: 'Science', topic: 'Human Reproduction', tutoringPrompt: 'Explain the menstrual cycle for Grade 11. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'life12_genetics', grade: 12, stream: 'Science', topic: 'Genetics: DNA Structure', tutoringPrompt: 'Explain DNA replication for Grade 12. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'life12_evolution', grade: 12, stream: 'Science', topic: 'Evolution by Natural Selection', tutoringPrompt: 'Explain Darwinism for Grade 12. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' }
  ],
  'English FAL': [
    { id: 'eng10_poetry', grade: 10, stream: 'Science', topic: 'Figures of Speech in Poetry', tutoringPrompt: 'Act as an expert Grade 10 English teacher. Explain figures of speech such as metaphors, similes, and personification. Provide clear definitions and multiple examples from Grade 10 literature. Return JSON: {"explanation": "string", "examples": "string", "formula": "none"}.', questionPrompt: 'Generate 3 poetry analysis questions for Grade 10. Return JSON array.' },
    { id: 'eng11_novel', grade: 11, stream: 'Science', topic: 'Novel: Theme and Character', tutoringPrompt: 'Explain themes in Grade 11 literature. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'eng12_transactional', grade: 12, stream: 'Science', topic: 'Transactional Writing: Letters', tutoringPrompt: 'Explain formal letter formats for Grade 12. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'eng11_summary', grade: 11, stream: 'Science', topic: 'Summary Writing (7 Points)', tutoringPrompt: 'Explain 7-point summaries for Grade 11. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' },
    { id: 'eng12_comprehension', grade: 12, stream: 'Science', topic: 'Critical Language Awareness', tutoringPrompt: 'Explain identifying bias in Grade 12. Return JSON: {"explanation": "text", "formula": "none"}.', questionPrompt: 'Generate 3 questions. Return JSON array.' }
  ]
};